name: hackathon
type: drupal
docroot: backend/web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
composer_root: backend
web_environment: []
corepack_enable: true
